# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: voluntarily
    build: .
    command: gunicorn -b 0.0.0.0:5000 voluntarily.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/voluntarily.db
    volumes:
      - ./voluntarily:/code/voluntarily
      - ./db/:/db/
    ports:
      - "5000:5000"
